### PR TITLE
Remove aeoid - use integrated openid supprt

### PR DESCRIPTION
**Pull request by jamezpolley**
Removes the double-login for admins. 

Makes testing easier, as you're now either logged-in or logged-out, the two half-logged-in states are removed.

When creating a talk offer, there must be a creator. Under the old code, this would be an aeoid_user - but the admin might not be logged into openid, in which case aeoid happily creates the object and auto_assigns the owner "Null". So you'd need to write something extra to force the admin to be logged into openid too.

Switching to a single userbase removes this problem.

The only current use of aeoid_users is for the event responses, so this code will look for responses owned by the user who just logged in and attach the google user object to the gcreated field. Once the majority of these are populated we can use a mapreduce to move the current created_by entries into a new field and then move gcreated_by into created_by and all will be good...

This change is reversible. We can never change the auth settings back from "federated" to "just google", but that doesn't mean we can't reactivate the aeoid, in the event that we decide google's support is insufficient.

### CODE REVIEW

**Comment by mithro** [comment]
Following comments on the code:
- Video autoplay stuff should be in a different pull request.
- Can you fix up the commit comments or do a squash commit?
- We don't have enough users that just discarding the responses after the next meeting is a problem.

Following comments about the openid stuff;

Negatives;
- Using aeoid allows us to extend it to add facebook or other non-openid support.
- aeoid can have practically infinite login length, google's is limited to 4 weeks, meaning every month people will have to relogin.
- aeoid is probably closer to the django stuff?

Positives;
- Removing the dual user systems is kinda nice - but we could do the same by just removing the Google authentication and just using aeoid.

I don't really care enough to block this change, but I would like you to fix up the code comments.

**Comment by jamezpolley** [comment]
> - Using aeoid allows us to extend it to add facebook or other non-openid support.

Sure, but we can do this anyway. Using the integrated auth lets us handle that complexity when it becomes useful, instead of paying for the complexity now and not getitng anything out of it

> - aeoid can have practically infinite login length, google's is limited to 4 weeks, meaning every month people will have to relogin.
>   I'm not sure why this is a 'negative'. Once they've identified once to the app, future requests should just be a single click with maybe a confirmation screen if they have multiple logins and need to choose an account.
> 
> aeoid is probably closer to the django stuff?

From memory, the most significant difference is that django's inbuilt models don't have "auto_current_user_add", but that's simple to add by a few lines overriding the save() method on the model. Theoretically, the fact that aeoid_users have actual db models that we can access makes it more similar; in practice, aeoid hides the models fairly successfully and you don't use the model anyway.

> we could do the same by just removing the Google authentication and just using aeoid.
>  we'd have to implement a way to distinguish admin users from non-admins, which implies some kind of group management...

Will work on squashing and removing the non-autoplay

**Comment by jamezpolley** [comment]
Squashed. No autoplay.

**Comment by jamezpolley** [comment]
Mrmmf. Pylint on this makes me sad, but most of the issues are in the offer\* files, which were incomplete at the time this fork was made. Will tidy them later.

**Pull request merged**
